### ISSUE TITLE
[0.2.0] TO DO List

### ISSUE THREAD

**Issue by daita** [nextcloud/social#152]
- [ ] Security: Check origin of object during an import (to avoid instance Z to edit information regarding instance Y)
- [ ] Bug: Do not create Post if no field is filled (example case: direct message to a non existant user)
- [ ] Feature: Like on a Post #104 
- [ ] Feature: ~~Retweet~~ Repeat on a Post #105 
- [ ] Feature: Manage attachment (at least image and link) #106 #107 
- [ ] Manage local account @account
- [ ] ReplyTo
- [ ] Delete Message

**Comment by juliushaertl** [comment]
@daita Can we just create separate issues and use the milestone for tracking? Otherwise we have two separate lists which need to be maintained.
