### ISSUE TITLE
TODO first alpha 0.1 🥚

### ISSUE THREAD

**Issue by daita** [nextcloud/social#54]
See 0.1 🥚 milestone at https://github.com/nextcloud-gmbh/social/milestone/1

Technical debt to sort out before alpha release:
- [x] ~Prune node modules from history for quick cloning~: https://github.com/nextcloud-gmbh/social/issues/65 (@juliushaertl)
- [x] Use migrations for database https://github.com/nextcloud-gmbh/social/issues/11
- [x] Using sqlite is broken #55

Bugs & features:
- [ ] Security: Check ids of object during an import (to avoid instance Z to edit information regarding instance Y). (@daita)
- [x] Security: Check parents/sons chain on external request (import) (@daita)
- [x] Security: Block any remote request while the app is not configured. (@daita)
- [x] Security: Filter content from all request (html tags ?) (@daita)
- [x] Security: Filter content based on mime type when caching document (jpeg/png/gif) (@daita)
- [X] Improvement: Managing cache (cron) (@daita)
- [x] Improvement: Manage (network) request. Based on the number of request during the creation of the Post. Generating a queue. Including a retry-on-fail. (@daita)
- [x] UX: testing the cloud adress, testing the webfinger (mod_rewrite) during the installation process #75  (@juliushaertl)
- [x] UI: Search for a remote account #76  (@juliushaertl)
- [x] UI: follow/unfollow account  (@juliushaertl)
- [x] UI: Responsive design #98 (@juliushaertl)
- [x] UI: Profile view with followers/following accounts #99 (@juliushaertl)

Small fixes/checks (@daita):

- [x] Check the propagation of the privacy level of InstancePaths on followers (followers-only)
- [ ] Testing the queue on real network issues
- [x] /apps/social/@nonexistantuser should returns an error
- [x] /apps/social/api/v1/actor/avatar?id=nonexistantuser - should returns a better error
- [x] webfinger must returns an error is no account
- [x] check if all request with IdString can/must be set with CS=false
- [x] setTimeout on different type of requests/instancePath
- [ ] Bug: Do not create Post if no field is filled (example case: direct message to a non existant user)
- [ ] ~~Create a log file in appdata containing request~~

## Out of scope
- [ ] Feature: Like on a Post #104 
- [ ] ~~replyTo - check privacy level when replying~~ (UI: @juliushaertl for 0.2 ?)
- [ ] Feature: ~~Retweet~~ Repeat on a Post #105 
- [ ] Feature: Manage attachment (at least image and link) #106 #107 
- [ ] Manage local account @account
