### ISSUE TITLE
[Roadmap] Alpha4 + Beta1

### ISSUE THREAD

**Issue by daita** [nextcloud/social#976]
### Alpha 4

- [ ] [core] Import/export account
- [ ] [core] Compat with ActivityStream and 3rdparty clients.
- [ ] [core] groups 
- [ ] [core] generate/clean/fix/replace HTML in Post (incoming/outgoing)
- [x] [backend] Chunking database/tables with dynamical index.
- [ ] [backend] Remove entries from tables (stream_dest and stream_act) on Unboost/Unlike/Delete/Post
- [ ] [backend] Account action: mute / report
- [ ] [frontend] creation of a Settings page with description of the account
- [ ] [frontend] Pin a Post (#125)
- [ ] [tools] remote test suite to test and pinpoint issue on the setup of the app.
- [x] [bugfix] Remove direct message from Home.
- [ ] [bugfix] link/redirection to local/remote account
- [ ] [bugfix] mentions on remote account
- [x] [nc] webfingerManager + fix #121 (https://github.com/nextcloud/server/pull/21817)

### Beta 1

- [ ] [Frontend] enable/disable auto-follow, list of pending following request.
- [ ] [Frontend] Photo gallery
- [ ] [Frontend] Video gallery (peertube)
- [ ] [Frontend] Implementing push events (feature from nc20)
- [ ] [Frontend] Chat friendly UI to display Direct Message

### Extras

- [ ] Support FullTextSearch+GlobalSearch (feature from nc20)
- [ ] opengraph
- [ ] nodeinfo

### Issues
- [x] [frontend] issue when sending a direct message an unknown account (#977)
- [ ] [backend] generate link within content on hashtags and mentions

@jospoortvliet @jancborchardt @karlitschek

**Comment by karlitschek** [comment]
Awesome plan.  👍

**Comment by rullzer** [comment]
>  [Frontend] Implementing push events (feature from nc20)

Push is still under discussion. But to start we can just have some polling maybe?

**Comment by rullzer** [comment]
* [ ] Notification on mention

For this you could use the default notification system. Then people would also get messages via push on their phone etc.

**Comment by jancborchardt** [comment]
@daita as discussed in the call, here are the things we should also integrate:
- Notifications when you are mentioned in a post by somebody
- Create and join private or public groups
- Profile page, link it up with user management?

**Comment by daita** [comment]
Adding new task for Alpha: 

- [activitypub] group management
- [core] generate/clean/fix/replace HTML in Post (incoming/outgoing)

**Comment by daita** [comment]
@jancborchardt  I created issues based on this thread. I guess we can close this one ?

**Comment by jancborchardt** [comment]
> @jancborchardt I created issues based on this thread. I guess we can close this one ?

Yup, perfect, thank you! :)
